name: 'Continuous Integration'
on:
  push:
    branches-ignore:
      - 'production'
    tags-ignore:
      - '*'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '.travis.yml'
      - '.gitignore'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths:
      - '**'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    env:
      GEMS_PATH: ~/vendor/bundle

    steps:

      - name: Deploy
        run: |
          bash tools/deploy.sh
